# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_awesome}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin MacKenzie IV"]
  s.date = %q{2010-10-31}
  s.description = %q{longer description of your gem}
  s.email = %q{sinisterchipmunk@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "acts_as_awesome.gemspec",
     "lib/acts_as_awesome.rb",
     "lib/acts_as_awesome/hook.rb",
     "lib/acts_as_awesome/instance_methods.rb",
     "lib/acts_as_awesome/railtie.rb",
     "test/helper.rb",
     "test/test_acts_as_awesome.rb",
     "test/test_app/.gitignore",
     "test/test_app/Gemfile",
     "test/test_app/README",
     "test/test_app/Rakefile",
     "test/test_app/app/controllers/application_controller.rb",
     "test/test_app/app/helpers/application_helper.rb",
     "test/test_app/app/views/layouts/application.html.erb",
     "test/test_app/config.ru",
     "test/test_app/config/application.rb",
     "test/test_app/config/boot.rb",
     "test/test_app/config/database.yml",
     "test/test_app/config/environment.rb",
     "test/test_app/config/environments/development.rb",
     "test/test_app/config/environments/production.rb",
     "test/test_app/config/environments/test.rb",
     "test/test_app/config/initializers/backtrace_silencers.rb",
     "test/test_app/config/initializers/inflections.rb",
     "test/test_app/config/initializers/mime_types.rb",
     "test/test_app/config/initializers/secret_token.rb",
     "test/test_app/config/initializers/session_store.rb",
     "test/test_app/config/locales/en.yml",
     "test/test_app/config/routes.rb",
     "test/test_app/db/seeds.rb",
     "test/test_app/doc/README_FOR_APP",
     "test/test_app/lib/tasks/.gitkeep",
     "test/test_app/public/404.html",
     "test/test_app/public/422.html",
     "test/test_app/public/500.html",
     "test/test_app/public/favicon.ico",
     "test/test_app/public/images/rails.png",
     "test/test_app/public/index.html",
     "test/test_app/public/javascripts/application.js",
     "test/test_app/public/javascripts/controls.js",
     "test/test_app/public/javascripts/dragdrop.js",
     "test/test_app/public/javascripts/effects.js",
     "test/test_app/public/javascripts/prototype.js",
     "test/test_app/public/javascripts/rails.js",
     "test/test_app/public/robots.txt",
     "test/test_app/public/stylesheets/.gitkeep",
     "test/test_app/script/rails",
     "test/test_app/test/performance/browsing_test.rb",
     "test/test_app/test/test_helper.rb",
     "test/test_app/vendor/plugins/.gitkeep"
  ]
  s.homepage = %q{http://github.com/sinisterchipmunk/acts_as_awesome}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{one-line summary of your gem}
  s.test_files = [
    "test/helper.rb",
     "test/test_acts_as_awesome.rb",
     "test/test_app/app/controllers/another_controller.rb",
     "test/test_app/app/controllers/application_controller.rb",
     "test/test_app/app/controllers/awesome_controller.rb",
     "test/test_app/app/helpers/another_helper.rb",
     "test/test_app/app/helpers/application_helper.rb",
     "test/test_app/app/helpers/awesome_helper.rb",
     "test/test_app/config/application.rb",
     "test/test_app/config/boot.rb",
     "test/test_app/config/environment.rb",
     "test/test_app/config/environments/development.rb",
     "test/test_app/config/environments/production.rb",
     "test/test_app/config/environments/test.rb",
     "test/test_app/config/initializers/backtrace_silencers.rb",
     "test/test_app/config/initializers/inflections.rb",
     "test/test_app/config/initializers/mime_types.rb",
     "test/test_app/config/initializers/secret_token.rb",
     "test/test_app/config/initializers/session_store.rb",
     "test/test_app/config/routes.rb",
     "test/test_app/db/seeds.rb",
     "test/test_app/test/functional/another_controller_test.rb",
     "test/test_app/test/functional/awesome_controller_test.rb",
     "test/test_app/test/performance/browsing_test.rb",
     "test/test_app/test/test_helper.rb",
     "test/test_app/test/unit/helpers/another_helper_test.rb",
     "test/test_app/test/unit/helpers/awesome_helper_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

